### ISSUE TITLE
Fix linking issues when using multiple codegen units

### ISSUE THREAD

**Issue by japaric** [rust-lang-nursery/embedded-wg#53]
To improve build times rustc is now defaulting to building crates using multiple codegen units. The
problem is that using multiple codegen units can sometimes break linking of no-std applications
("undefined reference to `rust_begin_unwind`").

We are looking for someone who can help us fix the problem in the compiler

### Tasks

- [ ] Tweak rustc linking process to properly support multiple codegen units. The problem and
  solution is described in https://github.com/rust-lang/rust/issues/47074#issuecomment-354588718

The current workaround for this issue is to force the compiler to use a single codegen unit in
Cargo.toml

``` toml
# workaround rust-lang/rust#47074
[profile.dev]
codegen-units = 1
incremental = false
```
